name: 'build'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install -g yarn
          yarn install

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          npm install -g yarn
          yarn install

      - name: Build the app
        run: yarn tauri build

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/msi/*.msi